import { Link } from "wouter";
import { useState } from "react";
import {
  CheckCircle2,
  Circle,
  Sparkles,
  Upload,
  ArrowRight,
  ArrowLeft,
  User,
  Building2,
  Briefcase,
  Home,
  FileText,
  ScanLine,
  ChevronRight,
  Plus,
  Mail,
  MapPin,
  Calendar,
} from "lucide-react";
import { PageHeader } from "../components/ui/PageHeader";
import { Card, CardHeader } from "../components/ui/Card";
import { Pill } from "../components/ui/Pill";
import { fmtUSD, cn } from "../lib/format";

type ClientType = "individual" | "scorp" | "ccorp" | "partnership" | "bookkeeping";

const CLIENT_TYPES: { id: ClientType; label: string; icon: typeof User; description: string; entities: string }[] = [
  { id: "individual", label: "Individual (1040)", icon: User, description: "W-2, 1099, rental, K-1 pass-through", entities: "Personal only" },
  { id: "scorp", label: "S Corporation", icon: Building2, description: "1120S filer with shareholders", entities: "Entity + shareholder personal" },
  { id: "ccorp", label: "C Corporation", icon: Briefcase, description: "1120 filer with disregarded entities", entities: "Entity + officers" },
  { id: "partnership", label: "Partnership / LLC", icon: Building2, description: "1065 filer with partner K-1s", entities: "Entity + partners" },
  { id: "bookkeeping", label: "Bookkeeping only", icon: Home, description: "Monthly bookkeeping engagement", entities: "Entity only" },
];

const STEPS = [
  { id: "type", label: "Client type" },
  { id: "identity", label: "Identity & docs" },
  { id: "intake", label: "Intake questionnaire" },
  { id: "review", label: "Review & confirm" },
];

export function Onboarding() {
  const [step, setStep] = useState(0);
  const [type, setType] = useState<ClientType>("individual");

  return (
    <div className="animate-fade-up">
      <div className="px-10 pt-10 max-w-[1280px]">
        <PageHeader
          eyebrow="New Client Onboarding · Phase 2 · Proposed"
          title={
            <>
              <span className="block">Onboarding,</span>
              <span className="italic" style={{ fontVariationSettings: '"opsz" 144, "SOFT" 100', fontWeight: 320 }}>
                in 4 minutes.
              </span>
            </>
          }
          subtitle="Structured intake by client type. AI-extracted driver's license. Questionnaire responses auto-populate the client record — no double entry. Document checklist generated by entity structure and prior history."
        />
      </div>

      <div className="px-10 pb-12 max-w-[1280px]">
        {/* Step indicator */}
        <div className="mb-10 flex items-center gap-3">
          {STEPS.map((s, i) => {
            const isActive = i === step;
            const isComplete = i < step;
            return (
              <div key={s.id} className="flex items-center gap-3">
                <div className={cn(
                  "flex items-center gap-2 px-3 py-2 rounded-sm transition-all",
                  isActive ? "bg-ink text-paper" : isComplete ? "text-ink" : "text-ink-faint"
                )}>
                  <div className={cn(
                    "w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-mono font-medium",
                    isActive ? "bg-paper text-ink" : isComplete ? "bg-emerald-deep text-paper" : "bg-paper-deep text-ink-muted"
                  )}>
                    {isComplete ? <CheckCircle2 size={11} strokeWidth={2.4} /> : i + 1}
                  </div>
                  <span className="text-[12.5px] font-medium">{s.label}</span>
                </div>
                {i < STEPS.length - 1 && <div className={cn("w-8 h-px", i < step ? "bg-emerald-deep" : "bg-ink/15")} />}
              </div>
            );
          })}
        </div>

        {/* STEP 0 — Type selection */}
        {step === 0 && (
          <Card>
            <CardHeader
              eyebrow="Step 1 of 4"
              title="What type of client?"
              description="Selection determines the questionnaire branch, entity setup workflow, and document checklist template."
            />
            <div className="grid grid-cols-3 gap-3 mt-2">
              {CLIENT_TYPES.map((t) => {
                const Icon = t.icon;
                const selected = type === t.id;
                return (
                  <button
                    key={t.id}
                    onClick={() => setType(t.id)}
                    className={cn(
                      "card p-5 text-left transition-all group hover:shadow-paper",
                      selected ? "ring-2 ring-ochre-500/50 bg-ochre-50/30" : ""
                    )}
                  >
                    <div className="flex items-baseline justify-between mb-3">
                      <Icon size={18} strokeWidth={1.5} className={selected ? "text-ochre-700" : "text-ink-soft"} />
                      <div className={cn(
                        "w-4 h-4 rounded-full border-2 transition-all",
                        selected ? "bg-ochre-500 border-ochre-500" : "border-ink/15"
                      )}>
                        {selected && <div className="w-1 h-1 bg-paper rounded-full m-auto mt-[5px]" />}
                      </div>
                    </div>
                    <div className="text-[14px] font-medium text-ink mb-1">{t.label}</div>
                    <div className="text-[11.5px] text-ink-muted leading-snug mb-3">{t.description}</div>
                    <div className="text-[10.5px] eyebrow">{t.entities}</div>
                  </button>
                );
              })}
            </div>

            <div className="mt-6 flex justify-end">
              <button
                onClick={() => setStep(1)}
                className="flex items-center gap-2 px-4 py-2.5 text-[13px] font-medium bg-ink text-paper hover:bg-ink-soft transition-colors rounded-sm"
              >
                Continue
                <ArrowRight size={12} strokeWidth={1.8} />
              </button>
            </div>
          </Card>
        )}

        {/* STEP 1 — Identity + driver's license AI */}
        {step === 1 && (
          <div className="grid grid-cols-2 gap-6">
            <Card>
              <CardHeader
                eyebrow="Step 2 of 4 · Identity"
                title="Driver's license upload"
                description="AI extracts name, address, DOB, license number. ~14 fields populated automatically."
              />
              <div className="border-2 border-dashed border-ink/15 rounded-sm bg-paper-deep/40 p-8 text-center group hover:border-ochre-500/30 transition-colors mt-2">
                <ScanLine size={28} strokeWidth={1.4} className="text-ink-muted mx-auto mb-3" />
                <div className="text-[13px] font-medium text-ink mb-1">Drop driver's license here</div>
                <div className="text-[11.5px] text-ink-muted mb-4">JPG, PNG, or PDF · Front side only</div>
                <button className="px-3.5 py-2 text-[12.5px] font-medium border border-ink/15 hover:bg-paper-card transition-colors text-ink rounded-sm">
                  Choose file
                </button>
              </div>

              <div className="mt-5 p-4 bg-ochre-50/40 rounded-sm border-l-2 border-ochre-500">
                <div className="flex items-start gap-2.5">
                  <Sparkles size={13} strokeWidth={1.8} className="text-ochre-700 mt-0.5 shrink-0" />
                  <p className="text-[12px] text-ink-soft leading-relaxed">
                    Already extracted from prior upload: <span className="font-medium text-ink">Marian R. Tucker, FL DL T-261-538-72-401-0</span>.
                    Confidence 0.99. <button className="text-ochre-700 underline">Use this</button>.
                  </p>
                </div>
              </div>
            </Card>

            <Card>
              <CardHeader
                eyebrow="AI extraction · live"
                title="Identity fields"
              />
              <div className="space-y-2.5 text-[13px] mt-2">
                {[
                  { label: "Full name", value: "Jeffrey Lawrence Tucker", confidence: 1.0 },
                  { label: "Date of birth", value: "08/14/1971", confidence: 1.0 },
                  { label: "Address", value: "4218 Bayshore Blvd", confidence: 0.99 },
                  { label: "City, State, ZIP", value: "Sarasota, FL 34243", confidence: 1.0 },
                  { label: "DL Number", value: "T-261-538-72-401-0", confidence: 0.97 },
                  { label: "Issue date", value: "06/22/2023", confidence: 0.99 },
                  { label: "Expiration", value: "08/14/2031", confidence: 1.0 },
                ].map((row) => (
                  <div key={row.label} className="grid grid-cols-[110px_1fr_60px] items-baseline gap-3 border-b border-ink/6 pb-2 last:border-0">
                    <span className="text-[11px] eyebrow">{row.label}</span>
                    <span className="text-ink truncate">{row.value}</span>
                    <span className="text-[10.5px] tabular text-emerald-deep flex items-center gap-1 justify-end">
                      <Sparkles size={9} strokeWidth={1.8} />
                      {(row.confidence * 100).toFixed(0)}%
                    </span>
                  </div>
                ))}
              </div>

              <div className="mt-6 flex items-center justify-between">
                <button
                  onClick={() => setStep(0)}
                  className="flex items-center gap-1.5 text-[12.5px] text-ink-muted hover:text-ink transition-colors"
                >
                  <ArrowLeft size={12} strokeWidth={1.8} />
                  Back
                </button>
                <button
                  onClick={() => setStep(2)}
                  className="flex items-center gap-2 px-4 py-2.5 text-[13px] font-medium bg-ink text-paper hover:bg-ink-soft transition-colors rounded-sm"
                >
                  Continue
                  <ArrowRight size={12} strokeWidth={1.8} />
                </button>
              </div>
            </Card>
          </div>
        )}

        {/* STEP 2 — Intake questionnaire */}
        {step === 2 && (
          <Card>
            <CardHeader
              eyebrow="Step 3 of 4 · Questionnaire"
              title="Intake questions"
              description="Branched by client type. Responses generate the document request checklist for tax year 2024."
            />
            <div className="space-y-6 mt-4">
              {[
                { q: "What was your filing status for the most recent tax year?", a: "Married Filing Jointly", auto: true },
                { q: "Do you have ownership in any pass-through entities (S-Corp, partnership, LLC)?", a: "Yes — Tucker Holdings LLC (100%), Tucker Family RE Partnership (60%)", auto: true },
                { q: "Did you sell any real estate or investment property in 2024?", a: "No", auto: false },
                { q: "Do you own rental real estate?", a: "Yes — Bayshore Property Holdings LLC, residential rental", auto: true },
                { q: "Did you make any retirement plan contributions?", a: "Yes — SEP IRA ($69,000) + spousal IRA ($7,000)", auto: true },
                { q: "Did you receive any IRS notices in the past 12 months?", a: "No", auto: false },
                { q: "Did you incur any business meals, travel, or vehicle expenses through your S-Corp?", a: "Yes — see Tucker Holdings 1120S Schedule 1", auto: true },
              ].map((item, i) => (
                <div key={i} className="flex gap-4 pb-5 border-b border-ink/6 last:border-0">
                  <div className="display tabular text-[20px] text-ink-faint shrink-0 w-8" style={{ fontVariationSettings: '"opsz" 144, "SOFT" 30', fontWeight: 380 }}>
                    {String(i + 1).padStart(2, "0")}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="text-[13px] text-ink-soft leading-relaxed mb-2">{item.q}</div>
                    <div className="flex items-baseline gap-3">
                      <div className="text-[13.5px] text-ink leading-snug flex-1">{item.a}</div>
                      {item.auto && (
                        <Pill variant="ochre">
                          <Sparkles size={9} strokeWidth={1.8} />
                          Auto-populated from prior return
                        </Pill>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>

            <div className="mt-8 flex items-center justify-between">
              <button
                onClick={() => setStep(1)}
                className="flex items-center gap-1.5 text-[12.5px] text-ink-muted hover:text-ink transition-colors"
              >
                <ArrowLeft size={12} strokeWidth={1.8} />
                Back
              </button>
              <button
                onClick={() => setStep(3)}
                className="flex items-center gap-2 px-4 py-2.5 text-[13px] font-medium bg-ink text-paper hover:bg-ink-soft transition-colors rounded-sm"
              >
                Continue
                <ArrowRight size={12} strokeWidth={1.8} />
              </button>
            </div>
          </Card>
        )}

        {/* STEP 3 — Review */}
        {step === 3 && (
          <div className="grid grid-cols-3 gap-6">
            <div className="col-span-2">
              <Card>
                <CardHeader
                  eyebrow="Step 4 of 4 · Review"
                  title="Generated client record"
                  description="Auto-populated from driver's license + questionnaire + prior return data."
                />
                <div className="space-y-2.5 text-[13px] mt-2">
                  {[
                    { label: "Client", value: "Jeffrey L. & Marian R. Tucker" },
                    { label: "Filing status", value: "Married Filing Jointly" },
                    { label: "Address", value: "4218 Bayshore Blvd, Sarasota, FL 34243" },
                    { label: "Email (primary)", value: "j.tucker@tuckerholdings.us" },
                    { label: "Tier (recommended)", value: "Diamond" },
                    { label: "POD assigned", value: "Alpha · Marcus Tate (Tax Manager)" },
                    { label: "Entity links", value: "3 entities — Tucker Holdings LLC (S-Corp), Tucker Family RE Partnership, Bayshore Property Holdings LLC" },
                    { label: "Document checklist", value: "14 items generated" },
                    { label: "Estimated annual fee", value: fmtUSD(38400) },
                  ].map((row) => (
                    <div key={row.label} className="grid grid-cols-[160px_1fr] items-baseline gap-3 border-b border-ink/6 pb-2 last:border-0">
                      <span className="text-[11px] eyebrow">{row.label}</span>
                      <span className="text-ink">{row.value}</span>
                    </div>
                  ))}
                </div>

                <div className="mt-8 flex items-center justify-between">
                  <button
                    onClick={() => setStep(2)}
                    className="flex items-center gap-1.5 text-[12.5px] text-ink-muted hover:text-ink transition-colors"
                  >
                    <ArrowLeft size={12} strokeWidth={1.8} />
                    Back
                  </button>
                  <Link
                    to="/clients/60"
                    className="flex items-center gap-2 px-5 py-2.5 text-[13px] font-medium bg-emerald-deep text-paper hover:bg-emerald-deep/90 transition-colors rounded-sm"
                  >
                    <CheckCircle2 size={12} strokeWidth={2.2} />
                    Create client & open record
                  </Link>
                </div>
              </Card>
            </div>

            <div className="col-span-1 space-y-6">
              <Card>
                <CardHeader title="What happens next" eyebrow="Auto-triggered on creation" />
                <ul className="space-y-3 text-[12.5px]">
                  {[
                    "Document checklist sent to client portal",
                    "Magic-link invitation emailed to j.tucker@",
                    "Engagement letter draft routed to Marcus",
                    "Stripe payment session created for first-payment",
                    "Karbon Client Group + Contact synced",
                    "Ignition proposal queued",
                  ].map((item, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <CheckCircle2 size={11} strokeWidth={1.8} className="text-emerald-deep mt-0.5 shrink-0" />
                      <span className="text-ink-soft">{item}</span>
                    </li>
                  ))}
                </ul>
              </Card>

              <Card>
                <CardHeader title="Time elapsed" eyebrow="This intake" />
                <div className="display tabular text-[44px] text-ink leading-none" style={{ fontVariationSettings: '"opsz" 144, "SOFT" 30', fontWeight: 380 }}>
                  3:42
                </div>
                <div className="text-[11.5px] text-emerald-deep mt-2 tabular">
                  ↓ from 47 min industry average
                </div>
              </Card>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
